#!/bin/sh /etc/rc.common
# Copyright (C) 2015 OpenWrt.org

START=88
STOP=2

USE_PROCD=1
PROG=/usr/sbin/lircd

make_cmdline() {
	cmdline=" --nodaemon --loglevel=5"

	config_get driver lircd driver "devinput"
	cmdline="$cmdline --driver=$driver"

	config_get device lircd device "/dev/input/event0"
	cmdline="$cmdline --device=$device"
}

start_service() {
	config_load lirc

	config_get_bool enabled lircd 'enabled' 0
	[ $enabled -eq 0 ] && return

	# Create directory for socket and pid
	[ -d /var/run/lirc ] || {
		mkdir -m 0777 -p /var/run/lirc
	}

	# Build command params
	make_cmdline

	procd_open_instance
	logger -t 'lircd' "$cmdline"
	procd_set_param command "$PROG" $cmdline
	procd_close_instance
}

# Wait for service to exit and release sockets
reload_service() {
	stop
	sleep 2
	start
}

restart() {
	reload_service
}
