#!/bin/sh /etc/rc.common
# Copyright (C) 2015 OpenWrt.org

START=88
STOP=2

USE_PROCD=1
PROG=/usr/sbin/lircd

make_cmdline() {
	cmdline=" --nodaemon --loglevel=5"

	config_get driver lircd 'driver' "devinput"
	[ $driver -ne "" ] && cmdline="$cmdline --driver=$driver"

	config_get device options 'device' 0
	[ $device -ne 0 ] && cmdline="$cmdline --device=$device"
}

start_service() {
	config_load lirc

	config_get_bool enabled lircd 'enabled' 0
	[ $enabled -eq 0 ] && return

	# Build command params
	make_cmdline

	procd_open_instance
	logger -t 'lircd' "$cmdline"
	procd_set_param command "$PROG" $cmdline
	procd_close_instance
}

# Wait for service to exit and release sockets
reload_service() {
	stop
	sleep 2
	start
}

restart() {
	reload_service
}
